service: userver-serverless-image-resize-bucket

custom:
  secrets: ${file(../secrets/secrets.json)}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE, 'dev'}
  profile: ${env:PROFILE, 'default'}
  region: ${env:REGION, 'us-east-1'}
  environment:
    BUCKET: ${env:BUCKET}

resources:
  Resources:
    UServerImageResize:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicReadWrite
        BucketName: ${env:BUCKET}
        WebsiteConfiguration:
          ErrorDocument: error.html
          IndexDocument: index.html
    UServerImageResizePolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: UServerImageResize
        PolicyDocument:
          Statement:
            - Action:
                - "s3:*"
              Effect: "Allow"
              Resource:
                Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - Ref: UServerImageResize
                    - "/*"
              Principal: "*"
