version: "3"

services:
  userver-serverless-image-resize:
    container_name: userver-serverless-image-resize-deploy
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./secrets:/deploy/secrets
    env_file:
      - ./secrets/secrets.env
